TaskHive/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("management.urls", namespace="management")),
    path("accounts/", include("django.contrib.auth.urls")),
]

management/urls.py
from django.urls import path

from management.views import (
    index,
    WorkerListView,
    WorkerDetailView,
    TaskListView,
    TaskDetailView,
    assign_organization, ProjectListView, register, ProjectDetailView, TeamListView, TeamDetailView, WorkerUpdateView,
    profile, ProjectUpdateView, chat_view, ChatRoomListView, ChatRoomCreateView, chat_room, CommentListView,
    TaskCreateView, TaskUpdateView, ProjectCreateView, TeamCreateView, TeamUpdateView, add_comment, delete_comment,
    TaskDeleteView, ProjectDeleteView, TeamDeleteView, WorkerDeleteView, feedback_view, AboutView, login_view,
)

urlpatterns = [
    path("", index, name="index"),
    path("register", register, name="register"),
    path("profile", profile, name="profile"),
    path("login/", login_view, name="login"),
    #path("dashboard"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update", WorkerUpdateView.as_view(), name="worker-update"),
    path("workers/<int:pk>/delete", WorkerDeleteView.as_view(), name="worker-delete"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("task/<int:pk>", TaskDetailView.as_view(), name="task-detail"),
    path("task/create", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/update", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete", TaskDeleteView.as_view(), name="task-delete"),
    path("projects/", ProjectListView.as_view(), name="project-list"),
    path("projects/<int:pk>", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/create", ProjectCreateView.as_view(), name="project-create"),
    path("projects/<int:pk>/update", ProjectUpdateView.as_view(), name="project-update"),
    path("projects/<int:pk>/delete", ProjectDeleteView.as_view(), name="project-delete"),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/<int:pk>", TeamDetailView.as_view(), name="team-detail"),
    path("teams/create", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("assign-organization/", assign_organization, name="assign-organization"),
    path("chats/", ChatRoomListView.as_view(), name="chat-list"),
    path("chat/<int:pk>", chat_room, name="chat-room"),
    path("chat/create", ChatRoomCreateView.as_view(), name="chat-create"),
    path("comments/", CommentListView.as_view(), name="comment-list"),
    path("tasks/<int:task_id>/add-comment", add_comment, name="add_comment"),
    path("comments/<int:comment_id>/delete", delete_comment, name="delete_comment"),
    path("feedback/submit/", feedback_view, name="feedback"),
    path("about/", AboutView.as_view(), name="about"),
]

app_name = "management"

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% query_transform page=page_obj.previous_page_number%}">Prev</a></li>
      {% endif %}
      <li class="page-item-active"><span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span></li>
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{% query_transform page=page_obj.next_page_number %}">Next</a></li>
      {% endif %}
    </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav menu-top">
    <li class="sidebar-user-block">
      <a href="{% url 'management:profile' %}">
        <iconify-icon icon="ic:round-account-circle"></iconify-icon>
      </a>
      {% if user.is_authenticated %}
        <span class="username">{{ user.username }}</span>
        {% else %}
          <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </li>
    <li>
      <a href="{% url 'management:index' %}">
        <iconify-icon icon="ic:round-dashboard"></iconify-icon>
      </a>
    </li>
    <li>
      <a href="{% url 'management:comment-list' %}">
        <iconify-icon icon="ion:notifications"></iconify-icon>
      </a>
    </li>
    <li>
      <a href="{% url 'management:chat-list' %}">
        <iconify-icon icon="flowbite:messages-solid"></iconify-icon>
      </a>
    </li>
    <li>
      <a href="{% url 'management:team-list' %}">
        <iconify-icon icon="fluent:people-team-20-filled"></iconify-icon>
      </a>
    </li>
    <li>
      <a href="{% url 'management:task-list' %}">
        <iconify-icon icon="pajamas:list-task"></iconify-icon>
      </a>
    </li>
    <li>
      <a href="{% url 'management:project-list' %}">
        <iconify-icon icon="fluent:projection-screen-text-sparkle-16-filled"></iconify-icon>
      </a>
    </li>
    <li>
      <a href="{% url 'management:about' %}">
        <iconify-icon icon="mingcute:question-line"></iconify-icon>
      </a>
    </li>
</ul>
<ul class="sidebar-nav menu-bottom">
    <li>
        <a href="{% url 'logout' %}">
            <iconify-icon icon="uil:exit"></iconify-icon>
        </a>
    </li>
</ul>